### PR TITLE
Allow to config custom templates

### PR DESCRIPTION
**Pull request by RapotOR**
I added some configuration to be able to modify the template location.

```
herzult_forum:
    templating:
        location:
            category:   HerzultForumBundle:Category
            forum:      HerzultForumBundle:Forum
            post:       HerzultForumBundle:Post
            topic:      HerzultForumBundle:Topic
```

### CODE REVIEW

**Comment by Herzult** [comment]
Why don't you use the bundle inheritance mechanism for this ?

**Comment by GromNaN** [comment]
Hey @Herzult, do you know a way to replace a template by one in an other bundle ?

**Comment by RapotOR** [comment]
It is a way, sure.

Having a new bundle is too much just to customize views; I think.
You give configuration for controllers, forms, ... etc ; but not for views.

`AppBundle + HerzultForumBundle` vs `AppBundle + HerzultForumBundle + CustomForumBundle`
What do you think?

**Comment by Herzult** [comment]
Yes, you're right, I does not make sense to allow it for controllers and not for views...

**Pull request merged**
