### PR TITLE
fix Declaration of getDefaultOptions()

### PR DESCRIPTION
**Pull request by hd-deman**

### CODE REVIEW

**Comment by ibasaw** [comment]
why this isn't in the master ? I use sf 2.1.4

I apply this fix to install properly, but it seem there are more to do...

when i try to create a new topic, i got this error
Expected argument of type "object, array or empty", "string" given 
it's in the topic controller...

How to fix this ?

**Comment by ibasaw** [comment]
is there anybody alive ?

**Comment by Nelrann** [comment]
+1

**Comment by Escaladeur** [comment]
@ibasaw  : Add the next lines in your composer.json. This allow you to use hd-deman repository whit dmitry.tsoy commit instant of herzult repository.

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/hd-deman/HerzultForumBundle"
    }
    ],
```

**Comment by HDouss** [comment]
I have the same issue than toinouu and ibasaw. Using hd-deman commits makes the declaration compatible with s2.1, but when creating a new topic, I have the exception : 
Expected argument of type "object, array or empty", "string" given 
I think it happens when the container tries to get 'herzult_forum.form.new_topic'.

**Comment by mablae** [comment]
Is this project dead? @Herzult PING :+1:

**Comment by Herzult** [comment]
If someone wants to maintain it, I can give him write access to the repository but I do it.

**Comment by gurgenhakobyan** [comment]
I'm also getting this "Expected argument of type "object, array or empty", "string" given. so it won't be fixed?

**Comment by msalsas** [comment]
I've created a new topic with this error. I had not seen this one. Of course, I have the same problem...

**Comment by msalsas** [comment]
Try this: https://github.com/Herzult/HerzultForumBundle/issues/54#issuecomment-19854123

**Comment by msalsas** [comment]
I had solved it, but it comes again. And I don't know why!

**Comment by msalsas** [comment]
This is the point where it fails:

In Controller/TopicController:

```
    $form = $this->get('herzult_forum.form.new_topic');
```

Expected argument of type "object, array or empty", "string" given 

Any idea?

**Pull request closed without merging**
